steps:
  - name: 'node:14'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install
        echo 'env variables:'
        echo $TRAKTCLIENTID
        echo TRAKTCLIENTSECRET
        node --experimental-modules run.mjs