steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        SECRETS=("TRAKTCLIENTID" "TRAKTCLIENTSECRET" "TMDBAPIKEY")
        for secret in "${SECRETS[@]}"; do
          export "${secret}"=$(gcloud secrets versions access latest --secret="${secret}" --format="get(payload.data)" | base64 -d)
        done

  - name: 'node:14'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install
        node --experimental-modules run.mjs

options:
  logging: 'CLOUD_LOGGING_ONLY'  # or 'NONE' if you don't want to store logs in Cloud Storage
  
build:
  serviceAccount: 'your-service-account-email@your-project-id.iam.gserviceaccount.com'
  logsBucket: 'your-custom-logs-bucket-name'