trigger: none

schedules:
  - cron: "0 */12 * * *"
    displayName: "Every 12 hours"
    branches:
      include:
        - "*"

jobs:
  - job: sync
    displayName: Sync Lists
    pool:
      vmImage: "ubuntu-latest"

    steps:
      - download: current
        artifact: "myartifacts"

      - script: |
          TRAKTACCESSTOKEN=$(cat $(Pipeline.Workspace)/myartifacts/accessToken.txt)
          echo "My variable value is: $TRAKTACCESSTOKEN"
        displayName: "Read Artifact and Set Variable"

      # - script: |
      #     rm -rf $(Build.ArtifactStagingDirectory)/*
      #   displayName: "Delete Artifacts"
      #   condition: succeeded()

      # - script: |
      #     npm install
      #     node --experimental-modules run.mjs
      #   displayName: "Run Script"

      # - task: PublishBuildArtifacts@1
      #   inputs:
      #     pathtoPublish: "accessToken.txt"
      #     artifactName: "accessToken"
      #     publishLocation: "Container"
      #   displayName: "Publish Artifact"
