trigger: none

schedules:
  - cron: "0 */12 * * *"
    displayName: "Every 12 hours"
    branches:
      include:
        - "*"

jobs:
  - job: sync
    displayName: Sync Lists
    pool:
      vmImage: "ubuntu-latest"

    steps:
      # - task: DownloadPipelineArtifact@2
      #   inputs:
      #     artifactName: 'access-token.txt'
      #     path: '$(Pipeline.Workspace)/downloaded-artifacts'
      #     runVersion: 'latest'
      #     continueOnError: true

      # - script: |
      #     TRAKTACCESSTOKEN=$(cat $(Pipeline.Workspace)/access-token/access-token.txt)
      #     echo "My variable value is: $TRAKTACCESSTOKEN"
      #   displayName: "Read Artifact and Set Variable"
      #   continueOnError: true

      # - script: |
      #     npm install
      #     node --experimental-modules run.mjs
      #   displayName: "Run Script"
      #   continueOnError: true

      - script: |
          ls -l $(Build.SourcesDirectory)
          
      - task: PublishBuildArtifacts@1
        inputs:
          targetPath: '$(Build.SourcesDirectory)/access-token.txt'

          artifactName: "access-token"
        displayName: "Publish Artifact"
        continueOnError: true
