schedules:
- cron: "0 4 * * *"
  displayName: "Every day at 4 AM"
  branches:
    include:
    - main
    
variables:
  - group: ApiKeys

jobs:
  - job: sync
    displayName: Sync Lists
    pool:
      vmImage: "ubuntu-latest"

    steps:
      - script: |
          npm install
          node --experimental-modules run.mjs
        displayName: "Run Script"