trigger: none

schedules:
  - cron: "0 */12 * * *"
    displayName: "Every 12 hours"
    branches:
      include:
        - "*"

jobs:
  - job: sync
    displayName: Sync Lists
    pool:
      vmImage: "ubuntu-latest"

    steps:
      - script: |
          ls $(Build.ArtifactStagingDirectory)
      - task: DownloadPipelineArtifact@2
        inputs:
          artifactName: 'access-token'
          path: '$(Pipeline.Workspace)/downloaded-artifacts'
          runVersion: 'latest'
          continueOnError: true

      - script: |
          TRAKTACCESSTOKEN=$(cat $(Pipeline.Workspace)/downloaded-artifacts/access-token/access-token.txt)
          echo "My variable value is: $TRAKTACCESSTOKEN"
        displayName: "Read Artifact and Set Variable"
        continueOnError: true

      - script: |
          npm install
          node --experimental-modules run.mjs
        displayName: "Run Script"
        continueOnError: true

      - task: CopyFiles@2
        displayName: 'Copy access-token.txt'
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)'
          Contents: 'access-token.txt'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact'
        inputs:
          PathToPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'access-token'
        continueOnError: true

