trigger:
  - none

schedules:
  - cron: "0 */12 * * *"
    displayName: "Every 12 hours"
    branches:
      include:
        - "*"

pr:
  - "*"

pool:
  vmImage: "ubuntu-latest"

jobs:
- job: 'letterboxd-to-trakt'
  displayName: Sync Lists
  steps:
    - script: |
        npm install
        node --experimental-modules run.mjs
      displayName: "Run Script"
