trigger: none

schedules:
  - cron: "0 */12 * * *"
    displayName: "Every 12 hours"
    branches:
      include:
        - "*"

jobs:
  - job: sync
    displayName: Sync Lists
    pool:
      vmImage: "ubuntu-latest"

    steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          artifactName: 'accessToken.txt'
          path: '$(Pipeline.Workspace)/downloaded-artifacts'
          runVersion: 'latest'
          continueOnError: true

      - script: |
          TRAKTACCESSTOKEN=$(cat $(Pipeline.Workspace)/accessToken.txt)
          echo "My variable value is: $TRAKTACCESSTOKEN"
        displayName: "Read Artifact and Set Variable"
        continueOnError: true

      - script: |
          npm install
          node --experimental-modules run.mjs
        displayName: "Run Script"
        continueOnError: true

      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: "accessToken.txt"
          artifactName: "accessToken"
          publishLocation: "Container"
        displayName: "Publish Artifact"
        continueOnError: true
