trigger:
  - none

variables:
  TRAKTCLIENTID: ""
  TRAKTCLIENTSECRET: ""
  TMDBAPIKEY: ""

schedules:
  - cron: "0 */12 * * *"
    displayName: "Every 12 hours"
    branches:
      include:
        - "*"

pr:
  - "*"

pool:
  vmImage: "ubuntu-latest"

steps:
  - script: |
      npm install
      node --experimental-modules run.mjs
    displayName: "Run Script"
